apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: n6interface
  namespace: 4g
spec:
  config: '{
    "cniVersion": "0.3.1",
    "type": "macvlan",
    "master": "eno8",
    "mode": "bridge",
    "ipam": {
    "type": "static"
    }
    }'
