apiVersion: v1
kind: ConfigMap
metadata:
  name: nwdaf-config
  namespace: 4g
data:
  settings.json: |
    {
        "host": "192.168.100.18:8088",
        "mHost": "mongodb://mongo-0.mongo:27017,mongo-1.mongo:27017,mongo-2.mongo:27017/Slice_settings?replicaSet=rs0",
        "MDbName": "Slice_settings",
        "MUser": "Y3VtdWNvcmVucmY=",
        "MPwd": "udY3VtdWNvcmVucmY=r",
        "nrf_url": "192.168.100.11:9090",
        "cnc_url": "192.168.100.12:3000",
        "cert": "./public.crt",
        "key": "./private.key",
        "uiCertkey": "./localhost-cert.pem",
        "uiprivkey": "./localhost-privkey.pem",
        "nfInstanceName": "NWDAF-1",
        "plmn": {
            "mcc": "244",
            "mnc": "44"
        },
        "fqdn": "192.168.100.18"
    }
