apiVersion: v1
kind: ConfigMap
metadata:
  name: hss-config
  namespace: 4g
data:
  hss-config.yml: |
    info:
      description: "Home Subscriber Server (HSS)"
      version: "4.3.0"

    configuration:
      addr: "192.168.100.16"
      diamPort: "3868" # standard diameter port
      ppaddr: ":9000"
      host: "hss.epc.mnc044.mcc244.pub.3gppnetwork.org"
      realm: "pub.3gppnetwork.org"
      enableDiamTls: false # set to true to enable hss diameter client send TLS request to mme
      dtls:
        certFile: ""  # provide key path for diameter server listen tls connection
        keyFile: ""   # provide key path for diameter server listen tls connection
      networkType: "sctp" # protocol type tcp/sctp
      # hss HTTP server configuration
      httpServerInfo:
        port: "20055"
        nfGroupId: "1"
        priority: 0
        nfInstanceName: "HSS"
        tls:
          certFile: "public.crt"
          keyFile: "private.key"
        useFqdn: false
        isRedundant: true
      plmnIdList:
          - mcc: "244"
            mnc: "44"
      nrfInfo:
        bindingIPv4: "192.168.100.11"
        port: "9090"
