---
apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: 4g
  labels:
    name: mongo
spec:
  ports:
    - port: 27017
      targetPort: 27017
  clusterIP: None
  selector:
    role: mongo
